#! /bin/sh

make   ARCH=arm CROSS_COMPILE=/home/giampa/toolchains/arm-cortex_a15/bin/arm-cortex_a15-linux-gnueabihf- -j5

echo 0

cp /home/giampa/HTCKernel49byGP/arch/arm/boot/zImage /home/giampa/boot

echo 1
/home/giampa/boot/mkbootimg --kernel /home/giampa/boot/zImage --ramdisk /home/giampa/boot/initramfs.cpio.gz --base 0x80600000 --cmdline 'console=ttyHSL0,115200,n8 androidboot.hardware=dlxpul user_debug=31' -o /home/giampa/boot/new_boot.img

echo 2

cp /home/giampa/boot/new_boot.img /home/giampa/host/ADB

echo 3

